### PR TITLE
fix: downloading binary with nx v15

### PR DESCRIPTION
**Pull request by jonmercarpio**
Hi, thanks for this library.

Just found an issue while downloading the binary file, seems like nx does not wait till the file is fully downloaded and the process concluded without scanning the project.

There is new version of `sonarqube-scanner: 3.0.0`, this one provide a new method for async scan.

Features:
- added new version of sonarqube-scanner
- wait for binary downloading and scanning process

### CODE REVIEW

**Comment by bnygld** [comment]
Hey @koliveira15 - any chance this could be released please? Same issues with nx `15.7.2`

**Comment by koliveira15** [comment]
@bnygld thanks for the contribution! @koliveira15/nx-sonarqube@2.1.2

**Comment by bnygld** [comment]
thanks to @jonmercarpio for the fix and you @koliveira15 for the plugin!

**Comment by koliveira15** [comment]
> thanks to @jonmercarpio for the fix and you @koliveira15 for the plugin!

thanks @jonmercarpio !

**Pull request merged**
